# Generated by Django 3.2.4 on 2021-06-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
    ]
